name: CI

on:
  push:
    branches: [main, 1.0-dev]
  pull_request:
    branches: [main, 1.0-dev]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv sync --extra dev
      - run: make lint unit-test